/* Auto-generated by genmsg_cpp for file /home/nick/Dropbox/ROS_Workspace/drc_common/feedback_devices/msg/tacta_belt.msg */
#ifndef FEEDBACK_DEVICES_MESSAGE_TACTA_BELT_H
#define FEEDBACK_DEVICES_MESSAGE_TACTA_BELT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace feedback_devices
{
template <class ContainerAllocator>
struct tacta_belt_ {
  typedef tacta_belt_<ContainerAllocator> Type;

  tacta_belt_()
  : header()
  , motors(0)
  , values()
  {
    values.assign(0.0);
  }

  tacta_belt_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , motors(0)
  , values()
  {
    values.assign(0.0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _motors_type;
  uint8_t motors;

  typedef boost::array<float, 16>  _values_type;
  boost::array<float, 16>  values;


  typedef boost::shared_ptr< ::feedback_devices::tacta_belt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feedback_devices::tacta_belt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct tacta_belt
typedef  ::feedback_devices::tacta_belt_<std::allocator<void> > tacta_belt;

typedef boost::shared_ptr< ::feedback_devices::tacta_belt> tacta_beltPtr;
typedef boost::shared_ptr< ::feedback_devices::tacta_belt const> tacta_beltConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::feedback_devices::tacta_belt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::feedback_devices::tacta_belt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace feedback_devices

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::feedback_devices::tacta_belt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::feedback_devices::tacta_belt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::feedback_devices::tacta_belt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6594452e6e5a30284436e89b1d1531a8";
  }

  static const char* value(const  ::feedback_devices::tacta_belt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6594452e6e5a3028ULL;
  static const uint64_t static_value2 = 0x4436e89b1d1531a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::feedback_devices::tacta_belt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "feedback_devices/tacta_belt";
  }

  static const char* value(const  ::feedback_devices::tacta_belt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::feedback_devices::tacta_belt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
uint8 motors\n\
float32[16] values\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::feedback_devices::tacta_belt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::feedback_devices::tacta_belt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::feedback_devices::tacta_belt_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::feedback_devices::tacta_belt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.motors);
    stream.next(m.values);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct tacta_belt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feedback_devices::tacta_belt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::feedback_devices::tacta_belt_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motors: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motors);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FEEDBACK_DEVICES_MESSAGE_TACTA_BELT_H

