/* Auto-generated by genmsg_cpp for file /home/nick/Dropbox/ROS_Workspace/drc_common/feedback_devices/msg/tacta_pr2_grippers.msg */
#ifndef FEEDBACK_DEVICES_MESSAGE_TACTA_PR2_GRIPPERS_H
#define FEEDBACK_DEVICES_MESSAGE_TACTA_PR2_GRIPPERS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace feedback_devices
{
template <class ContainerAllocator>
struct tacta_pr2_grippers_ {
  typedef tacta_pr2_grippers_<ContainerAllocator> Type;

  tacta_pr2_grippers_()
  : header()
  , rh_rf_freq(0)
  , rh_lf_freq(0)
  , rh_rf_amp(0)
  , rh_lf_amp(0)
  , lh_rf_freq(0)
  , lh_lf_freq(0)
  , lh_rf_amp(0)
  , lh_lf_amp(0)
  , rh_grip_quality()
  , lh_grip_quality()
  {
    rh_grip_quality.assign(0);
    lh_grip_quality.assign(0);
  }

  tacta_pr2_grippers_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , rh_rf_freq(0)
  , rh_lf_freq(0)
  , rh_rf_amp(0)
  , rh_lf_amp(0)
  , lh_rf_freq(0)
  , lh_lf_freq(0)
  , lh_rf_amp(0)
  , lh_lf_amp(0)
  , rh_grip_quality()
  , lh_grip_quality()
  {
    rh_grip_quality.assign(0);
    lh_grip_quality.assign(0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _rh_rf_freq_type;
  int32_t rh_rf_freq;

  typedef int32_t _rh_lf_freq_type;
  int32_t rh_lf_freq;

  typedef int32_t _rh_rf_amp_type;
  int32_t rh_rf_amp;

  typedef int32_t _rh_lf_amp_type;
  int32_t rh_lf_amp;

  typedef int32_t _lh_rf_freq_type;
  int32_t lh_rf_freq;

  typedef int32_t _lh_lf_freq_type;
  int32_t lh_lf_freq;

  typedef int32_t _lh_rf_amp_type;
  int32_t lh_rf_amp;

  typedef int32_t _lh_lf_amp_type;
  int32_t lh_lf_amp;

  typedef boost::array<int32_t, 6>  _rh_grip_quality_type;
  boost::array<int32_t, 6>  rh_grip_quality;

  typedef boost::array<int32_t, 6>  _lh_grip_quality_type;
  boost::array<int32_t, 6>  lh_grip_quality;


  typedef boost::shared_ptr< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct tacta_pr2_grippers
typedef  ::feedback_devices::tacta_pr2_grippers_<std::allocator<void> > tacta_pr2_grippers;

typedef boost::shared_ptr< ::feedback_devices::tacta_pr2_grippers> tacta_pr2_grippersPtr;
typedef boost::shared_ptr< ::feedback_devices::tacta_pr2_grippers const> tacta_pr2_grippersConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace feedback_devices

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f511160451a24188f64b49198493eca";
  }

  static const char* value(const  ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6f511160451a2418ULL;
  static const uint64_t static_value2 = 0x8f64b49198493ecaULL;
};

template<class ContainerAllocator>
struct DataType< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "feedback_devices/tacta_pr2_grippers";
  }

  static const char* value(const  ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
#uint8 RH_RF=0\n\
#uint8 RH_LF=1\n\
#uint8 LH_RF=3\n\
#uint8 LH_LF=4\n\
\n\
#int32[4] freq\n\
#int32[4] min_amp\n\
#int32[4] max_amp\n\
\n\
int32 rh_rf_freq\n\
int32 rh_lf_freq\n\
int32 rh_rf_amp\n\
int32 rh_lf_amp\n\
\n\
int32 lh_rf_freq\n\
int32 lh_lf_freq\n\
int32 lh_rf_amp\n\
int32 lh_lf_amp\n\
\n\
int32[6] rh_grip_quality\n\
int32[6] lh_grip_quality\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.rh_rf_freq);
    stream.next(m.rh_lf_freq);
    stream.next(m.rh_rf_amp);
    stream.next(m.rh_lf_amp);
    stream.next(m.lh_rf_freq);
    stream.next(m.lh_lf_freq);
    stream.next(m.lh_rf_amp);
    stream.next(m.lh_lf_amp);
    stream.next(m.rh_grip_quality);
    stream.next(m.lh_grip_quality);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct tacta_pr2_grippers_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::feedback_devices::tacta_pr2_grippers_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rh_rf_freq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rh_rf_freq);
    s << indent << "rh_lf_freq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rh_lf_freq);
    s << indent << "rh_rf_amp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rh_rf_amp);
    s << indent << "rh_lf_amp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rh_lf_amp);
    s << indent << "lh_rf_freq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lh_rf_freq);
    s << indent << "lh_lf_freq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lh_lf_freq);
    s << indent << "lh_rf_amp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lh_rf_amp);
    s << indent << "lh_lf_amp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lh_lf_amp);
    s << indent << "rh_grip_quality[]" << std::endl;
    for (size_t i = 0; i < v.rh_grip_quality.size(); ++i)
    {
      s << indent << "  rh_grip_quality[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.rh_grip_quality[i]);
    }
    s << indent << "lh_grip_quality[]" << std::endl;
    for (size_t i = 0; i < v.lh_grip_quality.size(); ++i)
    {
      s << indent << "  lh_grip_quality[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.lh_grip_quality[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FEEDBACK_DEVICES_MESSAGE_TACTA_PR2_GRIPPERS_H

