/* Auto-generated by genmsg_cpp for file /home/nick/Dropbox/ROS_Workspace/drc_common/feedback_devices/msg/tacta_wrist.msg */
#ifndef FEEDBACK_DEVICES_MESSAGE_TACTA_WRIST_H
#define FEEDBACK_DEVICES_MESSAGE_TACTA_WRIST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace feedback_devices
{
template <class ContainerAllocator>
struct tacta_wrist_ {
  typedef tacta_wrist_<ContainerAllocator> Type;

  tacta_wrist_()
  : header()
  , front(0.0)
  , back(0.0)
  , top(0.0)
  , bottom(0.0)
  , right(0.0)
  , left(0.0)
  {
  }

  tacta_wrist_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , front(0.0)
  , back(0.0)
  , top(0.0)
  , bottom(0.0)
  , right(0.0)
  , left(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _front_type;
  float front;

  typedef float _back_type;
  float back;

  typedef float _top_type;
  float top;

  typedef float _bottom_type;
  float bottom;

  typedef float _right_type;
  float right;

  typedef float _left_type;
  float left;


  typedef boost::shared_ptr< ::feedback_devices::tacta_wrist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feedback_devices::tacta_wrist_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct tacta_wrist
typedef  ::feedback_devices::tacta_wrist_<std::allocator<void> > tacta_wrist;

typedef boost::shared_ptr< ::feedback_devices::tacta_wrist> tacta_wristPtr;
typedef boost::shared_ptr< ::feedback_devices::tacta_wrist const> tacta_wristConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::feedback_devices::tacta_wrist_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::feedback_devices::tacta_wrist_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace feedback_devices

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::feedback_devices::tacta_wrist_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::feedback_devices::tacta_wrist_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::feedback_devices::tacta_wrist_<ContainerAllocator> > {
  static const char* value() 
  {
    return "02d2e353ab3ecfc5d117fcdebd3cc6cf";
  }

  static const char* value(const  ::feedback_devices::tacta_wrist_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x02d2e353ab3ecfc5ULL;
  static const uint64_t static_value2 = 0xd117fcdebd3cc6cfULL;
};

template<class ContainerAllocator>
struct DataType< ::feedback_devices::tacta_wrist_<ContainerAllocator> > {
  static const char* value() 
  {
    return "feedback_devices/tacta_wrist";
  }

  static const char* value(const  ::feedback_devices::tacta_wrist_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::feedback_devices::tacta_wrist_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float32 front\n\
float32 back\n\
float32 top\n\
float32 bottom\n\
float32 right\n\
float32 left\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::feedback_devices::tacta_wrist_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::feedback_devices::tacta_wrist_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::feedback_devices::tacta_wrist_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::feedback_devices::tacta_wrist_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.front);
    stream.next(m.back);
    stream.next(m.top);
    stream.next(m.bottom);
    stream.next(m.right);
    stream.next(m.left);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct tacta_wrist_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feedback_devices::tacta_wrist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::feedback_devices::tacta_wrist_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "front: ";
    Printer<float>::stream(s, indent + "  ", v.front);
    s << indent << "back: ";
    Printer<float>::stream(s, indent + "  ", v.back);
    s << indent << "top: ";
    Printer<float>::stream(s, indent + "  ", v.top);
    s << indent << "bottom: ";
    Printer<float>::stream(s, indent + "  ", v.bottom);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FEEDBACK_DEVICES_MESSAGE_TACTA_WRIST_H

