"""autogenerated by genpy from gui/updateValvePosRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class updateValvePosRequest(genpy.Message):
  _md5sum = "b9665840fbf97c3697c336af0754e611"
  _type = "gui/updateValvePosRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseStamped valve
float32 radius
string id
float32 rms_err
float32 angle_err

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['valve','radius','id','rms_err','angle_err']
  _slot_types = ['geometry_msgs/PoseStamped','float32','string','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       valve,radius,id,rms_err,angle_err

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(updateValvePosRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.valve is None:
        self.valve = geometry_msgs.msg.PoseStamped()
      if self.radius is None:
        self.radius = 0.
      if self.id is None:
        self.id = ''
      if self.rms_err is None:
        self.rms_err = 0.
      if self.angle_err is None:
        self.angle_err = 0.
    else:
      self.valve = geometry_msgs.msg.PoseStamped()
      self.radius = 0.
      self.id = ''
      self.rms_err = 0.
      self.angle_err = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs))
      _x = self.valve.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7df.pack(_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w, _x.radius))
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2f.pack(_x.rms_err, _x.angle_err))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.valve is None:
        self.valve = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.valve.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.valve.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w, _x.radius,) = _struct_7df.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8')
      else:
        self.id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.rms_err, _x.angle_err,) = _struct_2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs))
      _x = self.valve.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7df.pack(_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w, _x.radius))
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2f.pack(_x.rms_err, _x.angle_err))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.valve is None:
        self.valve = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.valve.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.valve.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w, _x.radius,) = _struct_7df.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8')
      else:
        self.id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.rms_err, _x.angle_err,) = _struct_2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2f = struct.Struct("<2f")
_struct_7df = struct.Struct("<7df")
"""autogenerated by genpy from gui/updateValvePosResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class updateValvePosResponse(genpy.Message):
  _md5sum = "2eb271f340f821fdeeb17eb834a1f86e"
  _type = "gui/updateValvePosResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string success_code
geometry_msgs/PoseStamped valve


================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['success_code','valve']
  _slot_types = ['string','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success_code,valve

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(updateValvePosResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.success_code is None:
        self.success_code = ''
      if self.valve is None:
        self.valve = geometry_msgs.msg.PoseStamped()
    else:
      self.success_code = ''
      self.valve = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.success_code
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs))
      _x = self.valve.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.valve is None:
        self.valve = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.success_code = str[start:end].decode('utf-8')
      else:
        self.success_code = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.valve.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.valve.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.success_code
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs))
      _x = self.valve.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.valve is None:
        self.valve = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.success_code = str[start:end].decode('utf-8')
      else:
        self.success_code = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.valve.header.seq, _x.valve.header.stamp.secs, _x.valve.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.valve.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.valve.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.valve.pose.position.x, _x.valve.pose.position.y, _x.valve.pose.position.z, _x.valve.pose.orientation.x, _x.valve.pose.orientation.y, _x.valve.pose.orientation.z, _x.valve.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
class updateValvePos(object):
  _type          = 'gui/updateValvePos'
  _md5sum = 'a96e2de37474a8f9f0a1ca665dede876'
  _request_class  = updateValvePosRequest
  _response_class = updateValvePosResponse
